// Canonical identity of agents, sessions, and tasks. Crane always issues its own identifiers
// (ses_, tsk_, agt_, ins_), derived deterministically so every hook process of one session maps to
// the same records. Identifiers reported by a provider are stored next to them with their
// provenance and never overwritten by a different value; when a provider reports none, Crane
// generates a hashed identifier, records that it did, and never presents it as the provider's.

use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use super::model::Safety;
use crate::platform::files::{write_atomic, Lock};
use crate::platform::io_error;
use crate::trust::crypto::digest;

/** Where an identifier came from
 * Variants
    - Provider - reported by the agent provider
    - Environment - supplied through CRANE_SESSION_ID or CRANE_TASK_ID
    - Generated - generated by Crane because nothing was supplied
*/
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum Provenance {
    Provider,
    Environment,
    Generated,
}

/** A context file supplied to a session with its policy
 * Fields
    - policy: String - policy name
    - path: String - context file
    - digest: String - content digest supplied
*/
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct SuppliedContext {
    pub(crate) policy: String,
    pub(crate) path: String,
    pub(crate) digest: String,
}

/** One agent session
 * Fields
    - foxx_session_id: String - canonical identifier
    - provider: String - claude, codex, or generic
    - provider_session_id: Option<String> - as reported, None when not reported
    - provenance: Provenance - origin of the identity
    - agent_id: String - stable agent identity (provider in this repository)
    - agent_instance_id: String - agent instance of this session
    - model: Option<String> - model reported by the provider
    - models_seen: Vec<String> - every model reported during the session
    - cwd: Option<String> - working directory reported
    - started_at: u64 - Unix milliseconds
    - last_seen_at: u64 - Unix milliseconds
    - ended_at: Option<u64> - Unix milliseconds
    - end_reason: Option<String> - reason reported at the end
    - autonomy_mode: String - observe, assisted, delegated, or autonomous
    - safety: Safety - active, degraded, or quarantined
    - safety_reason: Option<String> - why the safety state changed
    - bypass_attempts: u64 - denied attempts to bypass Crane
    - violations: u64 - violations detected after the effect
    - current_task: Option<String> - canonical task being worked on
    - tasks: Vec<String> - every canonical task of the session
    - prompts: u64 - prompts submitted
    - registry_generation: u64 - registry generation when the session started
    - context: Vec<SuppliedContext> - context files supplied
    - conflicts: Vec<String> - identity conflicts observed
*/
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct SessionRecord {
    pub(crate) foxx_session_id: String,
    pub(crate) provider: String,
    pub(crate) provider_session_id: Option<String>,
    pub(crate) provenance: Provenance,
    pub(crate) agent_id: String,
    pub(crate) agent_instance_id: String,
    pub(crate) model: Option<String>,
    pub(crate) models_seen: Vec<String>,
    pub(crate) cwd: Option<String>,
    pub(crate) started_at: u64,
    pub(crate) last_seen_at: u64,
    pub(crate) ended_at: Option<u64>,
    pub(crate) end_reason: Option<String>,
    pub(crate) autonomy_mode: String,
    pub(crate) safety: Safety,
    pub(crate) safety_reason: Option<String>,
    pub(crate) bypass_attempts: u64,
    pub(crate) violations: u64,
    pub(crate) current_task: Option<String>,
    pub(crate) tasks: Vec<String>,
    pub(crate) prompts: u64,
    pub(crate) registry_generation: u64,
    pub(crate) context: Vec<SuppliedContext>,
    pub(crate) conflicts: Vec<String>,
}

/** One task: a unit of work inside a session, opened by each prompt unless the provider or
 * CRANE_TASK_ID names the task
 * Fields
    - foxx_task_id: String - canonical identifier
    - foxx_session_id: String - session
    - external_task_id: Option<String> - tracker identifier from CRANE_TASK_ID
    - provider_task_id: Option<String> - provider task identifier, if reported
    - provenance: Provenance - origin of the identity
    - name: Option<String> - CRANE_TASK_NAME, if given (prompts are never stored)
    - sequence: u64 - prompt number within the session (0 for the bootstrap task)
    - prompt_digest: Option<String> - SHA-512 of the prompt, never the prompt itself
    - prompt_chars: Option<u64> - prompt length
    - started_at: u64 - Unix milliseconds
    - ended_at: Option<u64> - Unix milliseconds
    - status: String - RUNNING, COMPLETED, BLOCKED, or ENDED
*/
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct TaskRecord {
    pub(crate) foxx_task_id: String,
    pub(crate) foxx_session_id: String,
    pub(crate) external_task_id: Option<String>,
    pub(crate) provider_task_id: Option<String>,
    pub(crate) provenance: Provenance,
    pub(crate) name: Option<String>,
    pub(crate) sequence: u64,
    pub(crate) prompt_digest: Option<String>,
    pub(crate) prompt_chars: Option<u64>,
    pub(crate) started_at: u64,
    pub(crate) ended_at: Option<u64>,
    pub(crate) status: String,
}

/** Derive a short canonical identifier
 * Input
    - prefix: &str - identifier prefix such as "ses"
    - domain: &str - digest domain
    - parts: &[&str] - inputs
 * Output
    - String such as "ses_0f3a..." (24 hex characters after the prefix)
*/
pub(crate) fn derive_id(prefix: &str, domain: &str, parts: &[&str]) -> String {
    let parts = parts.iter().map(|part| part.as_bytes()).collect::<Vec<_>>();
    format!("{prefix}_{}", &digest(domain, &parts)[..24])
}

/** What a hook knows about the session it belongs to
 * Fields
    - provider: String - claude, codex, or generic
    - provider_session_id: Option<String> - as reported
    - model: Option<String> - as reported
    - cwd: Option<String> - as reported
    - autonomy_mode: String - mode from the configuration
    - registry_generation: u64 - current registry generation
*/
#[derive(Debug, Clone)]
pub(crate) struct Observed {
    pub(crate) provider: String,
    pub(crate) provider_session_id: Option<String>,
    pub(crate) model: Option<String>,
    pub(crate) cwd: Option<String>,
    pub(crate) autonomy_mode: String,
    pub(crate) registry_generation: u64,
}

/** Identity records of one repository
 * Fields
    - directory: PathBuf - runtime directory
*/
#[derive(Debug, Clone)]
pub(crate) struct IdentityStore {
    directory: PathBuf,
}

impl IdentityStore {
    /** Open the identity records in a runtime directory
     * Input
        - directory: &Path - runtime directory
     * Output
        - IdentityStore
    */
    pub(crate) fn open(directory: &Path) -> Self {
        Self {
            directory: directory.to_path_buf(),
        }
    }

    /** Take the identity lock, held while a session or task is read, changed, and written
     * Input
        - None (uses self)
     * Output
        - Result<Lock, String>
    */
    pub(crate) fn lock(&self) -> Result<Lock, String> {
        Lock::acquire(&self.directory.join("identity.lock"))
    }

    /** Load a session
     * Input
        - id: &str - canonical session identifier
     * Output
        - Option<SessionRecord>
    */
    pub(crate) fn session(&self, id: &str) -> Option<SessionRecord> {
        read(&self.directory.join("sessions").join(format!("{id}.json")))
    }

    /** Save a session
     * Input
        - session: &SessionRecord - record
     * Output
        - Result<(), String>
    */
    pub(crate) fn save_session(&self, session: &SessionRecord) -> Result<(), String> {
        write(
            &self
                .directory
                .join("sessions")
                .join(format!("{}.json", session.foxx_session_id)),
            session,
        )
    }

    /** Load a task
     * Input
        - id: &str - canonical task identifier
     * Output
        - Option<TaskRecord>
    */
    pub(crate) fn task(&self, id: &str) -> Option<TaskRecord> {
        read(&self.directory.join("tasks").join(format!("{id}.json")))
    }

    /** Save a task
     * Input
        - task: &TaskRecord - record
     * Output
        - Result<(), String>
    */
    pub(crate) fn save_task(&self, task: &TaskRecord) -> Result<(), String> {
        write(
            &self
                .directory
                .join("tasks")
                .join(format!("{}.json", task.foxx_task_id)),
            task,
        )
    }

    /** List every session, most recently active first
     * Input
        - None (uses self)
     * Output
        - Vec<SessionRecord>
    */
    pub(crate) fn sessions(&self) -> Vec<SessionRecord> {
        let mut sessions = list(&self.directory.join("sessions"));
        sessions.sort_by_key(|session: &SessionRecord| std::cmp::Reverse(session.last_seen_at));
        sessions
    }

    /** List every task, most recent first
     * Input
        - None (uses self)
     * Output
        - Vec<TaskRecord>
    */
    pub(crate) fn tasks(&self) -> Vec<TaskRecord> {
        let mut tasks = list(&self.directory.join("tasks"));
        tasks.sort_by_key(|task: &TaskRecord| std::cmp::Reverse(task.started_at));
        tasks
    }

    /** Find or create the session a hook belongs to: the canonical identifier is derived from
     * the repository, provider, and provider session identifier; without one, from
     * CRANE_SESSION_ID; without that, Crane generates one from the provider, working directory,
     * and day, and marks it generated
     * Input
        - repository_id: &str - repository identity
        - observed: &Observed - what the hook reported
        - now: u64 - Unix milliseconds
     * Output
        - (SessionRecord, bool) the session and whether it was created
    */
    pub(crate) fn resolve_session(
        &self,
        repository_id: &str,
        observed: &Observed,
        now: u64,
    ) -> (SessionRecord, bool) {
        let environment = std::env::var("CRANE_SESSION_ID")
            .ok()
            .filter(|value| !value.is_empty());
        let (key, provenance) = match (&observed.provider_session_id, &environment) {
            (Some(id), _) => (id.clone(), Provenance::Provider),
            (None, Some(id)) => (id.clone(), Provenance::Environment),
            (None, None) => (
                format!(
                    "generated:{}:{}",
                    observed.cwd.clone().unwrap_or_default(),
                    now / 86_400_000
                ),
                Provenance::Generated,
            ),
        };
        let id = derive_id(
            "ses",
            "identity/session/v1",
            &[repository_id, &observed.provider, &key],
        );
        if let Some(mut session) = self.session(&id) {
            session.last_seen_at = now;
            if let Some(model) = &observed.model {
                if !session.models_seen.contains(model) {
                    session.models_seen.push(model.clone());
                }
                session.model = Some(model.clone());
            }
            if let (Some(recorded), Some(reported)) = (&session.cwd, &observed.cwd) {
                if recorded != reported
                    && !session
                        .conflicts
                        .iter()
                        .any(|conflict| conflict.contains(reported))
                {
                    session.conflicts.push(format!(
                        "working directory changed from {recorded} to {reported}"
                    ));
                }
            }
            return (session, false);
        }
        let session = SessionRecord {
            foxx_session_id: id.clone(),
            provider: observed.provider.clone(),
            provider_session_id: observed.provider_session_id.clone(),
            provenance,
            agent_id: derive_id(
                "agt",
                "identity/agent/v1",
                &[repository_id, &observed.provider],
            ),
            agent_instance_id: derive_id("ins", "identity/instance/v1", &[&id]),
            model: observed.model.clone(),
            models_seen: observed.model.iter().cloned().collect(),
            cwd: observed.cwd.clone(),
            started_at: now,
            last_seen_at: now,
            ended_at: None,
            end_reason: None,
            autonomy_mode: observed.autonomy_mode.clone(),
            safety: Safety::Active,
            safety_reason: None,
            bypass_attempts: 0,
            violations: 0,
            current_task: None,
            tasks: Vec::new(),
            prompts: 0,
            registry_generation: observed.registry_generation,
            context: Vec::new(),
            conflicts: Vec::new(),
        };
        (session, true)
    }

    /** Open a new task in a session: named by CRANE_TASK_ID (external) or the provider when
     * given, otherwise generated from the session and prompt number
     * Input
        - session: &mut SessionRecord - session (its current task is updated)
        - provider_task_id: Option<String> - provider task identifier
        - prompt: Option<&str> - prompt text, digested and never stored
        - now: u64 - Unix milliseconds
     * Output
        - Result<TaskRecord, String>
    */
    pub(crate) fn start_task(
        &self,
        session: &mut SessionRecord,
        provider_task_id: Option<String>,
        prompt: Option<&str>,
        now: u64,
    ) -> Result<TaskRecord, String> {
        if let Some(previous) = session.current_task.as_ref().and_then(|id| self.task(id)) {
            if previous.status == "RUNNING" && previous.sequence > 0 {
                let mut previous = previous;
                previous.status = "ENDED".into();
                previous.ended_at = Some(now);
                self.save_task(&previous)?;
            }
        }
        let external = std::env::var("CRANE_TASK_ID")
            .ok()
            .filter(|value| !value.is_empty());
        let sequence = if prompt.is_some() {
            session.prompts + 1
        } else {
            0
        };
        if prompt.is_some() {
            session.prompts += 1;
        }
        let (key, provenance) = match (&provider_task_id, &external) {
            (Some(id), _) => (format!("provider:{id}"), Provenance::Provider),
            (None, Some(id)) => (format!("external:{id}:{sequence}"), Provenance::Environment),
            (None, None) => (format!("generated:{sequence}"), Provenance::Generated),
        };
        let id = derive_id("tsk", "identity/task/v1", &[&session.foxx_session_id, &key]);
        let task = TaskRecord {
            foxx_task_id: id.clone(),
            foxx_session_id: session.foxx_session_id.clone(),
            external_task_id: external,
            provider_task_id,
            provenance,
            name: std::env::var("CRANE_TASK_NAME")
                .ok()
                .filter(|value| !value.is_empty()),
            sequence,
            prompt_digest: prompt.map(|prompt| crate::trust::crypto::sha512_hex(prompt.as_bytes())),
            prompt_chars: prompt.map(|prompt| prompt.chars().count() as u64),
            started_at: now,
            ended_at: None,
            status: "RUNNING".into(),
        };
        self.save_task(&task)?;
        if !session.tasks.contains(&id) {
            session.tasks.push(id.clone());
        }
        session.current_task = Some(id);
        Ok(task)
    }
}

/** Read a JSON record
 * Input
    - path: &Path - file
 * Output
    - Option<T>, None when missing or malformed
*/
fn read<T: for<'de> Deserialize<'de>>(path: &Path) -> Option<T> {
    serde_json::from_str(&fs::read_to_string(path).ok()?).ok()
}

/** Write a JSON record atomically
 * Input
    - path: &Path - file
    - value: &T - record
 * Output
    - Result<(), String>
*/
fn write<T: Serialize>(path: &Path, value: &T) -> Result<(), String> {
    let text = serde_json::to_string_pretty(value).map_err(io_error)?;
    write_atomic(path, text.as_bytes())
}

/** Read every JSON record in a directory
 * Input
    - directory: &Path - directory
 * Output
    - Vec<T>
*/
fn list<T: for<'de> Deserialize<'de>>(directory: &Path) -> Vec<T> {
    fs::read_dir(directory)
        .map(|entries| {
            entries
                .filter_map(Result::ok)
                .filter_map(|entry| read(&entry.path()))
                .collect()
        })
        .unwrap_or_default()
}
