// The compact zone map: .crane/zones.map lists one target per line with its criticality and
// autonomy ("payments/service.py::PaymentService.charge critical assisted"). It is a human's draft:
// nothing in it governs agents until `crane zones approve map` compiles it, through the ordinary
// zone model, into one zone per (criticality, autonomy) group with deterministic ids and writes
// them to .crane/zones/zones-map.zone. The authority engine therefore never learns a new format,
// and the zone set version changes only when an approved map changes the compiled zones.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io::ErrorKind;
use std::path::PathBuf;

use serde_json::{json, Value};

use super::model::{
    load as load_zones, parse, set_version, Autonomy, Criticality, Selector, SelectorKind, Zone,
};
use super::resolve::select;
use super::review::{actor, audit, directory, log, require_human, write, CONFIRM_LENGTH};
use crate::inventory::Inventory;
use crate::proposals::store::agent_environment;
use crate::repository::root;
use crate::util::{io_error, now_unix, sha256};

/** The map file, relative to .crane */
pub(crate) const MAP_FILE: &str = "zones.map";

/** The zone file an approved map compiles to, relative to .crane */
pub(crate) const COMPILED_FILE: &str = "zones/zones-map.zone";

/** First line of the compiled zone file, which marks it as written by a map approval */
const COMPILED_HEADER: &str = "# Generated by 'crane zones approve map' from .crane/zones.map";

/** Version of the map review record */
const MAP_REVIEW_FORMAT: u64 = 1;

/** One line of the map
 * Fields
    - number: usize - line number (1-based)
    - target: String - the target as written: a folder (DIR followed by a double-star segment),
      a file, "file::Symbol", or "file::Class.*"
    - selector: Selector - the zone selector the target compiles to
    - criticality: Criticality - declared criticality
    - autonomy: Autonomy - declared autonomy
    - note: Option<String> - the comment after "#", if any
*/
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Line {
    pub(crate) number: usize,
    pub(crate) target: String,
    pub(crate) selector: Selector,
    pub(crate) criticality: Criticality,
    pub(crate) autonomy: Autonomy,
    pub(crate) note: Option<String>,
}

impl Line {
    /** Return the autonomy this line leaves after its criticality's cap
     * Input
        - None (uses self)
     * Output
        - Autonomy
    */
    fn effective(&self) -> Autonomy {
        self.autonomy.min(self.criticality.autonomy_cap())
    }

    /** Describe the line for reports
     * Input
        - None (uses self)
     * Output
        - String such as "line 3 (payments/service.py critical assisted)"
    */
    pub(crate) fn label(&self) -> String {
        format!(
            "line {} ({} {} {})",
            self.number,
            self.target,
            self.criticality.name(),
            self.autonomy.name()
        )
    }
}

/** Turn a map target into a zone selector: a folder ending in a double-star segment is a folder,
 * "file::Name" a symbol in that file (patterns allowed in both parts), anything else a file path
 * or file pattern
 * Input
    - target: &str - target as written
 * Output
    - Result<Selector, String>
    - Error explaining the accepted forms
*/
fn selector_of(target: &str) -> Result<Selector, String> {
    let target = target.strip_prefix("./").unwrap_or(target);
    if target.starts_with('/') || target.split(['/', ':']).any(|part| part == "..") {
        return Err(format!(
            "target '{target}' must be relative to the repository root"
        ));
    }
    if let Some((file, name)) = target.split_once("::") {
        if file.is_empty() || name.is_empty() || file.ends_with('/') {
            return Err(format!(
                "target '{target}' must be FILE::Symbol or FILE::Class.*"
            ));
        }
        return Ok(Selector {
            kind: SelectorKind::Symbol,
            value: target.into(),
        });
    }
    if let Some(folder) = target.strip_suffix("/**") {
        if folder.is_empty() {
            return Err("the whole repository cannot be a target; name a folder as DIR/**".into());
        }
        return Ok(Selector {
            kind: SelectorKind::Folder,
            value: folder.into(),
        });
    }
    if target.ends_with('/') || target == "**" {
        return Err(format!(
            "target '{target}' names a folder; write it as DIR/**"
        ));
    }
    Ok(Selector {
        kind: SelectorKind::Path,
        value: target.into(),
    })
}

/** Parse the map text: "<target> <criticality> <autonomy> [# note]" per line, with blank lines and
 * lines starting with "#" ignored
 * Input
    - content: &str - map text
 * Output
    - Result<Vec<Line>, Vec<String>> the lines, or every error with its line number
*/
pub(crate) fn parse_map(content: &str) -> Parsed {
    let mut lines = Vec::new();
    let mut errors = Vec::new();
    for (index, raw) in content.lines().enumerate() {
        let number = index + 1;
        let trimmed = raw.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let (body, note) = match [" #", "\t#"]
            .iter()
            .filter_map(|marker| trimmed.find(marker))
            .min()
        {
            Some(at) => (
                trimmed[..at].trim(),
                Some(
                    trimmed[at..]
                        .trim_start()
                        .trim_start_matches('#')
                        .trim()
                        .to_string(),
                )
                .filter(|note| !note.is_empty()),
            ),
            None => (trimmed, None),
        };
        let error = |message: String| format!("{MAP_FILE}: line {number}: {message}");
        let words = body.split_whitespace().collect::<Vec<_>>();
        let [target, criticality, autonomy] = words[..] else {
            errors.push(error(format!(
                "expected '<target> <criticality> <autonomy> [# note]', found {} word{}",
                words.len(),
                if words.len() == 1 { "" } else { "s" }
            )));
            continue;
        };
        let parsed = selector_of(target).and_then(|selector| {
            Ok(Line {
                number,
                target: target.strip_prefix("./").unwrap_or(target).into(),
                selector,
                criticality: Criticality::parse(criticality)?,
                autonomy: Autonomy::parse(autonomy)?,
                note: note.clone(),
            })
        });
        match parsed {
            Ok(line) => lines.push(line),
            Err(message) => errors.push(error(message)),
        }
    }
    if errors.is_empty() {
        Ok(lines)
    } else {
        Err(errors)
    }
}

/** The result of parsing a map: its lines, or every error with its line number */
pub(crate) type Parsed = Result<Vec<Line>, Vec<String>>;

/** Return the deterministic id of the zone holding one (criticality, autonomy) group
 * Input
    - criticality: Criticality - criticality
    - autonomy: Autonomy - autonomy
 * Output
    - String such as "map_critical_assisted"
*/
pub(crate) fn zone_id(criticality: Criticality, autonomy: Autonomy) -> String {
    format!("map_{}_{}", criticality.name(), autonomy.name())
}

/** Compile map lines into zone file text: one zone per (criticality, autonomy) group, groups and
 * selectors sorted, so reordering, reformatting, or re-annotating the map changes nothing
 * Input
    - lines: &[Line] - parsed lines
 * Output
    - String zone file text (empty when there are no lines)
*/
pub(crate) fn compile(lines: &[Line]) -> String {
    let mut groups: BTreeMap<(Criticality, Autonomy), BTreeSet<String>> = BTreeMap::new();
    for line in lines {
        groups
            .entry((line.criticality, line.autonomy))
            .or_default()
            .insert(line.selector.text());
    }
    let mut text = String::new();
    for ((criticality, autonomy), selectors) in groups {
        text.push_str(&format!(
            "zone {} {{\n    criticality {};\n    autonomy {};\n",
            zone_id(criticality, autonomy),
            criticality.name(),
            autonomy.name()
        ));
        for selector in selectors {
            text.push_str(&format!("    select {selector};\n"));
        }
        text.push_str("}\n\n");
    }
    text
}

/** Compile map lines into zones through the ordinary zone model
 * Input
    - lines: &[Line] - parsed lines
 * Output
    - Result<Vec<Zone>, String>
*/
pub(crate) fn zones_of(lines: &[Line]) -> Result<Vec<Zone>, String> {
    parse(&compile(lines), COMPILED_FILE)
}

/** Compute the digest a reviewer confirms: of the compiled zone text, so it changes exactly when
 * what would govern changes
 * Input
    - lines: &[Line] - parsed lines
 * Output
    - String SHA-256 digest
*/
pub(crate) fn digest(lines: &[Line]) -> String {
    sha256(compile(lines).as_bytes())
}

/** What one line covers in the current repository
 * Fields
    - whole: BTreeSet<usize> - files every change to which it restricts
    - entities: BTreeSet<usize> - symbols it restricts (all symbols of whole files included)
*/
struct Coverage {
    whole: BTreeSet<usize>,
    entities: BTreeSet<usize>,
}

/** Resolve each line against the inventory
 * Input
    - inventory: &Inventory - current inventory
    - lines: &[Line] - parsed lines
 * Output
    - Vec<Coverage> aligned with lines
*/
fn coverage(inventory: &Inventory, lines: &[Line]) -> Vec<Coverage> {
    lines
        .iter()
        .map(|line| {
            let (_, entities, files) = select(inventory, &line.selector);
            Coverage {
                whole: if line.selector.kind == SelectorKind::Symbol {
                    BTreeSet::new()
                } else {
                    files
                },
                entities,
            }
        })
        .collect()
}

/** Find the lines a stricter rule fully shadows: everything the line covers is also covered by
 * lines that are at least as strict on both criticality and autonomy and stricter on one (or, for
 * identical values, by an earlier line), so the line changes no decision
 * Input
    - inventory: &Inventory - current inventory
    - lines: &[Line] - parsed lines
 * Output
    - Vec<(usize, Vec<usize>)> index of each shadowed line and the indices of the lines shadowing it
*/
pub(crate) fn shadows(inventory: &Inventory, lines: &[Line]) -> Vec<(usize, Vec<usize>)> {
    let covered = coverage(inventory, lines);
    let mut found = Vec::new();
    for (index, line) in lines.iter().enumerate() {
        let mine = &covered[index];
        if mine.entities.is_empty() && mine.whole.is_empty() {
            continue; // unresolved, reported as such
        }
        let stricter = |other: &Line| {
            let same =
                other.criticality == line.criticality && other.effective() == line.effective();
            other.criticality >= line.criticality
                && other.effective() <= line.effective()
                && (!same || other.number < line.number)
        };
        let by = lines
            .iter()
            .enumerate()
            .filter(|(other, candidate)| *other != index && stricter(candidate))
            .filter(|(other, _)| {
                let theirs = &covered[*other];
                !theirs.entities.is_disjoint(&mine.entities)
                    || !theirs.whole.is_disjoint(&mine.whole)
            })
            .map(|(other, _)| other)
            .collect::<Vec<_>>();
        let whole = by
            .iter()
            .flat_map(|other| covered[*other].whole.iter().copied())
            .collect::<BTreeSet<_>>();
        let entities = by
            .iter()
            .flat_map(|other| covered[*other].entities.iter().copied())
            .collect::<BTreeSet<_>>();
        if !by.is_empty() && mine.whole.is_subset(&whole) && mine.entities.is_subset(&entities) {
            found.push((index, by));
        }
    }
    found
}

/** Return the map file path
 * Input
    - None
 * Output
    - Result<PathBuf, String>
*/
fn map_path() -> Result<PathBuf, String> {
    Ok(root()?.join(MAP_FILE))
}

/** Read and parse the map
 * Input
    - None
 * Output
    - Result<Option<Parsed>, String> the parse result, None when there is no map
*/
pub(crate) fn read() -> Result<Option<Parsed>, String> {
    match fs::read_to_string(map_path()?) {
        Ok(text) => Ok(Some(parse_map(&text))),
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(None),
        Err(error) => Err(io_error(error)),
    }
}

/** Return the map review record path, kept apart from the recommendation records
 * Input
    - None
 * Output
    - Result<PathBuf, String>
*/
fn record_path() -> Result<PathBuf, String> {
    Ok(directory()?.join("map").join("review.json"))
}

/** Load the map review record
 * Input
    - None
 * Output
    - Result<Option<Value>, String>
*/
fn load_record() -> Result<Option<Value>, String> {
    match fs::read_to_string(record_path()?) {
        Ok(text) => serde_json::from_str(&text)
            .map(Some)
            .map_err(|error| format!("the zone map review record is invalid: {error}")),
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(None),
        Err(error) => Err(io_error(error)),
    }
}

/** Describe the map against the repository: its lines, the compiled zones and their digest,
 * shadowed and unresolved lines, and whether the approved map still matches
 * Input
    - inventory: &Inventory - current inventory
 * Output
    - Result<Value, String> {exists, errors, lines, zones, compiled, digest, shadowed, unresolved,
      approved_digest, state}
*/
pub(crate) fn status(inventory: &Inventory) -> Result<Value, String> {
    let record = load_record()?;
    let approved = record
        .as_ref()
        .and_then(|record| record["activation"]["digest"].as_str().map(String::from));
    let Some(parsed) = read()? else {
        return Ok(json!({
            "exists": false,
            "approved_digest": approved,
            "state": if approved.is_some() { "removed after approval; review and approve it to remove its zones" } else { "none" },
        }));
    };
    let lines = match parsed {
        Ok(lines) => lines,
        Err(errors) => {
            return Ok(
                json!({"exists": true, "errors": errors, "approved_digest": approved, "state": "invalid"}),
            )
        }
    };
    let digest = digest(&lines);
    let covered = coverage(inventory, &lines);
    let shadowed = shadows(inventory, &lines)
        .into_iter()
        .map(|(index, by)| {
            json!({
                "line": lines[index].number,
                "target": lines[index].target,
                "message": format!(
                    "{} is fully shadowed by {}",
                    lines[index].label(),
                    by.iter().map(|other| lines[*other].label()).collect::<Vec<_>>().join(", ")
                ),
                "by": by.iter().map(|other| lines[*other].number).collect::<Vec<_>>(),
            })
        })
        .collect::<Vec<_>>();
    let unresolved = lines
        .iter()
        .zip(&covered)
        .filter(|(_, coverage)| coverage.entities.is_empty() && coverage.whole.is_empty())
        .map(|(line, _)| json!({"line": line.number, "target": line.target, "message": format!("{} matches nothing in the repository; its zone will be degraded", line.label())}))
        .collect::<Vec<_>>();
    let state = match &approved {
        Some(approved) if *approved == digest => "active",
        Some(_) => "changed since approval",
        None => "not approved",
    };
    Ok(json!({
        "exists": true,
        "lines": lines.iter().map(|line| json!({
            "line": line.number,
            "target": line.target,
            "selector": line.selector.text(),
            "criticality": line.criticality.name(),
            "autonomy": line.autonomy.name(),
            "zone_id": zone_id(line.criticality, line.autonomy),
            "note": line.note,
        })).collect::<Vec<_>>(),
        "zones": zones_of(&lines)?.iter().map(|zone| zone.zone_id.clone()).collect::<Vec<_>>(),
        "compiled": compile(&lines),
        "digest": digest,
        "shadowed": shadowed,
        "unresolved": unresolved,
        "approved_digest": approved,
        "state": state,
    }))
}

/** Review the map: describe it and record the revision a human reviews (a new revision whenever
 * the compiled zones change); in an agent environment nothing is recorded
 * Input
    - inventory: &Inventory - current inventory
    - by: Option<String> - reviewer
 * Output
    - Result<Value, String> the status with the review record
    - Error if there is no map or it is invalid
*/
pub(crate) fn review(inventory: &Inventory, by: Option<String>) -> Result<Value, String> {
    let mut value = status(inventory)?;
    if value["exists"] == false && value["approved_digest"].is_null() {
        return Err(format!(
            "there is no .crane/{MAP_FILE}; write one line per target: '<target> <criticality> <autonomy> [# note]'"
        ));
    }
    if let Some(errors) = value["errors"].as_array() {
        return Err(errors
            .iter()
            .filter_map(Value::as_str)
            .collect::<Vec<_>>()
            .join("\n"));
    }
    let digest = value["digest"]
        .as_str()
        .map_or_else(|| sha256(b""), String::from);
    let mut record = load_record()?.unwrap_or_else(|| {
        json!({
            "map_review_format": MAP_REVIEW_FORMAT,
            "id": "map",
            "status": "none",
            "revision": 0,
            "digest": null,
            "history": [],
            "activation": null,
            "rejection": null,
        })
    });
    if record["digest"] != digest.as_str() && agent_environment().is_none() {
        let by = actor(by);
        record["revision"] = json!(record["revision"].as_u64().unwrap_or(0) + 1);
        record["digest"] = json!(digest);
        record["zone_text"] = json!(value["compiled"].as_str().unwrap_or_default());
        record["status"] = json!(if record["activation"]["digest"] == digest.as_str() {
            "approved"
        } else {
            "proposed"
        });
        record["rejection"] = Value::Null;
        log(&mut record, "reviewed", &by, json!({}));
        write(record_path()?, &record)?;
    }
    value["record"] = record;
    value["approve"] = json!(format!(
        "crane zones approve map --approver YOUR_NAME --confirm {}",
        digest
            .trim_start_matches("sha256:")
            .chars()
            .take(CONFIRM_LENGTH)
            .collect::<String>()
    ));
    Ok(value)
}

/** Approve the map: human-only, quoting the reviewed digest, which must still be the digest of
 * the map on disk; writes the compiled zones to .crane/zones/zones-map.zone (removing it when the
 * map is empty or gone), validates them through the zone model, and records the decision in the
 * audit log; approving the same map again changes nothing
 * Input
    - approver: Option<String> - who approves (required)
    - confirm: Option<String> - at least the first 12 characters of the digest
 * Output
    - Result<Value, String> the record, with already_approved
*/
pub(crate) fn approve(approver: Option<String>, confirm: Option<String>) -> Result<Value, String> {
    require_human("approve")?;
    let approver = approver
        .filter(|name| !name.trim().is_empty())
        .ok_or("crane zones approve map requires --approver NAME")?;
    let lines = match read()? {
        None => Vec::new(),
        Some(Ok(lines)) => lines,
        Some(Err(errors)) => return Err(errors.join("\n")),
    };
    let digest = digest(&lines);
    let mut record = load_record()?
        .filter(|record| record["digest"] == digest.as_str())
        .ok_or("the zone map changed since it was reviewed; run 'crane zones review map' first")?;
    if record["activation"]["digest"] == digest.as_str() {
        record["already_approved"] = json!(true);
        return Ok(record);
    }
    let quoted = confirm.unwrap_or_default();
    let quoted = quoted.trim_start_matches("sha256:");
    if quoted.len() < CONFIRM_LENGTH || !digest.trim_start_matches("sha256:").starts_with(quoted) {
        return Err(format!("crane zones approve map requires --confirm with at least the first {CONFIRM_LENGTH} characters of the reviewed digest (see 'crane zones review map')"));
    }
    let crane = root()?;
    let file = crane.join(COMPILED_FILE);
    let previous = fs::read_to_string(&file).ok();
    if previous
        .as_deref()
        .is_some_and(|text| !text.starts_with(COMPILED_HEADER))
    {
        return Err(format!(
            "{COMPILED_FILE} exists and was not written by a map approval; it is never overwritten"
        ));
    }
    let (before, _) = load_zones(&crane)?;
    let version_before = set_version(&before);
    let compiled = compile(&lines);
    if compiled.is_empty() {
        if previous.is_some() {
            fs::remove_file(&file).map_err(io_error)?;
        }
    } else {
        let text = format!("{COMPILED_HEADER} (digest {digest}); edit the map and approve it again, never this file\n\n{compiled}");
        fs::create_dir_all(crane.join("zones")).map_err(io_error)?;
        let temporary = file.with_extension(format!("zone.tmp{}", std::process::id()));
        fs::write(&temporary, text).map_err(io_error)?;
        fs::rename(&temporary, &file).map_err(io_error)?;
    }
    let (after, problems) = load_zones(&crane)?;
    if let Some(problem) = problems
        .iter()
        .find(|problem| problem.contains(COMPILED_FILE))
    {
        // An invalid compiled map never stays active
        match previous {
            Some(previous) => fs::write(&file, previous).map_err(io_error)?,
            None => {
                let _ = fs::remove_file(&file);
            }
        }
        return Err(format!("the zone map could not be activated: {problem}"));
    }
    let version_after = set_version(&after);
    record["status"] = json!("approved");
    record["activation"] = json!({"file": COMPILED_FILE, "digest": digest, "revision": record["revision"], "approver": approver, "at": now_unix(), "zone_set_version_before": version_before, "zone_set_version_after": version_after});
    log(
        &mut record,
        "approved",
        &approver,
        json!({"file": COMPILED_FILE}),
    );
    write(record_path()?, &record)?;
    audit(
        json!({"event": "zone_map_approved", "recommendation": "map", "revision": record["revision"], "digest": digest, "by": approver, "zone_set_version_before": version_before, "zone_set_version_after": version_after}),
    )?;
    record["already_approved"] = json!(false);
    Ok(record)
}

/** Reject the reviewed map revision: human-only; the active zones do not change
 * Input
    - approver: Option<String> - who rejects (required)
    - reason: Option<String> - why
 * Output
    - Result<Value, String> the record
*/
pub(crate) fn reject(approver: Option<String>, reason: Option<String>) -> Result<Value, String> {
    require_human("reject")?;
    let approver = approver
        .filter(|name| !name.trim().is_empty())
        .ok_or("crane zones reject map requires --approver NAME")?;
    let mut record = load_record()?
        .ok_or("the zone map has not been reviewed; run 'crane zones review map' first")?;
    if record["status"] != "proposed" {
        return Err(format!(
            "the zone map review is {}; only a proposed revision can be rejected",
            record["status"].as_str().unwrap_or("invalid")
        ));
    }
    record["status"] = json!("rejected");
    record["rejection"] = json!({"by": approver, "reason": reason, "at": now_unix(), "revision": record["revision"], "digest": record["digest"]});
    log(
        &mut record,
        "rejected",
        &approver,
        json!({"reason": reason}),
    );
    write(record_path()?, &record)?;
    audit(
        json!({"event": "zone_map_rejected", "recommendation": "map", "revision": record["revision"], "digest": record["digest"], "by": approver, "reason": reason}),
    )?;
    Ok(record)
}

/** Render a map review for a terminal
 * Input
    - value: &Value - result of review or approve
 * Output
    - String ending in a newline
*/
pub(crate) fn render(value: &Value) -> String {
    let text = |value: &Value| {
        value
            .as_str()
            .map_or_else(|| value.to_string(), String::from)
    };
    if value["id"] == "map" {
        // An approval or rejection record
        return format!(
            "Zone map revision {}: {}{}\n",
            value["revision"],
            text(&value["status"]),
            if value["already_approved"] == true {
                " (already approved; nothing changed)".to_string()
            } else if value["status"] == "approved" {
                format!(
                    "; {} now holds its zones (zone set version {})",
                    COMPILED_FILE,
                    text(&value["activation"]["zone_set_version_after"])
                )
            } else {
                String::new()
            }
        );
    }
    let mut out = format!(
        "Zone map .crane/{MAP_FILE}: {}\nDigest: {}\n",
        text(&value["state"]),
        text(&value["digest"])
    );
    for line in value["lines"].as_array().into_iter().flatten() {
        out.push_str(&format!(
            "  line {:<3} {:<48} {:<10} {:<10} -> {}{}\n",
            line["line"],
            text(&line["target"]),
            text(&line["criticality"]),
            text(&line["autonomy"]),
            text(&line["zone_id"]),
            line["note"]
                .as_str()
                .map_or(String::new(), |note| format!("  # {note}"))
        ));
    }
    for item in value["shadowed"]
        .as_array()
        .into_iter()
        .flatten()
        .chain(value["unresolved"].as_array().into_iter().flatten())
    {
        out.push_str(&format!("  ! {}\n", text(&item["message"])));
    }
    out.push_str(&format!("It compiles to {COMPILED_FILE}:\n"));
    for line in text(&value["compiled"]).lines() {
        out.push_str(&format!("    {line}\n"));
    }
    if value["state"] != "active" {
        out.push_str(&format!(
            "\nNext step (replace YOUR_NAME):\n  approve:  {}\n  reject:   crane zones reject map --approver YOUR_NAME --reason \"WHY\"\n",
            text(&value["approve"])
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::{compile, digest, parse_map, zones_of};

    /** Every form of target parses and errors carry line numbers */
    #[test]
    fn map_lines_parse_with_line_numbers() {
        let lines = parse_map(
            "# payments\n\npayments/** sensitive delegated   # the service\npayments/service.py critical assisted\npayments/service.py::PaymentService.charge restricted observe\npayments/service.py::PaymentService.* critical assisted\n",
        )
        .unwrap();
        assert_eq!(lines.len(), 4);
        assert_eq!(lines[0].selector.text(), "folder payments");
        assert_eq!(lines[0].note.as_deref(), Some("the service"));
        assert_eq!(lines[1].selector.text(), "path payments/service.py");
        assert_eq!(
            lines[2].selector.text(),
            "symbol payments/service.py::PaymentService.charge"
        );
        assert_eq!(lines[3].number, 6);
        let errors = parse_map(
            "a.py critical\nb.py red assisted\nc/ routine observe\n/abs.py routine observe\nd.py::  routine observe\nok.py routine autonomous\n",
        )
        .unwrap_err();
        assert_eq!(errors.len(), 5, "{errors:?}");
        assert!(errors[0].starts_with("zones.map: line 1: expected '<target>"));
        assert!(errors[1].contains("line 2: invalid criticality 'red'"));
        assert!(errors[2].contains("line 3: target 'c/' names a folder"));
        assert!(errors[3].contains("line 4:"));
        assert!(errors[4].contains("line 5:"));
    }

    /** Groups compile into ordinary zones with deterministic ids, and the digest ignores order,
     * spacing, and notes */
    #[test]
    fn compiled_zones_are_stable() {
        let first = parse_map(
            "b.py critical assisted\na/** routine autonomous\nc.py::X.y critical assisted # n\n",
        )
        .unwrap();
        let second = parse_map("\n# reordered\n  c.py::X.y    critical   assisted\na/**  routine  autonomous # notes do not count\nb.py critical assisted\n").unwrap();
        assert_eq!(compile(&first), compile(&second));
        assert_eq!(digest(&first), digest(&second));
        let zones = zones_of(&first).unwrap();
        let ids = zones
            .iter()
            .map(|zone| zone.zone_id.as_str())
            .collect::<Vec<_>>();
        assert_eq!(ids, ["map_routine_autonomous", "map_critical_assisted"]);
        assert_eq!(zones[1].selectors.len(), 2);
        assert_eq!(zones_of(&[]).unwrap(), Vec::new());
    }
}
